name = "web-vision-backend"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-20"
main = "build/worker/shim.mjs"

[build]
command = "cargo install -q worker-build --version ^0.0.8 && worker-build --release" # required

[[rules]]
globs = [ "**/*.wasm" ]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
